In [ ]:
import string
import pandas as pd
import numpy as np
import codecs
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import feature_extraction
from sklearn import linear_model
from sklearn import pipeline
from sklearn import metrics
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv("Language Detection.csv")
df.head()

Text Language
0   Nature, in the broadest sense, is the natural...  English
1  "Nature" can refer to the phenomena of the phy...  English
2  The study of nature is a large, if not the onl...  English
3  Although humans are part of nature, human acti...  English
4  [1] The word nature is borrowed from the Old F...  English

In [ ]:
df_eng = df[df['Language'] == 'English']['Text']
df_eng.head()
  

0     Nature, in the broadest sense, is the natural...
1    "Nature" can refer to the phenomena of the phy...
2    The study of nature is a large, if not the onl...
3    Although humans are part of nature, human acti...
4    [1] The word nature is borrowed from the Old F...
Name: Text, dtype: object

In [ ]:
df_ger = df[df['Language'] == 'German']['Text']
df_ger.head()

9498    .Wir sind alle auf der Suche nach schnellen We...
9499    Ich weiß, ich verstehe, was passiert, ist, das...
9500                            Wie wäre es also mit uns?
9501    Lernen Sie einige intelligente neue englische ...
9502    Also werden wir heute 10 neue intelligente Wör...
Name: Text, dtype: object

In [ ]:
df_spa = df[df['Language'] == 'Spanish']['Text']
df_spa.head()

4810    Nature es una de las más prestigiosas revistas...
4811    Su primer número fue publicado el 4 de noviemb...
4812    [2]​ Con una periodicidad semanal, la revista ...
4813    Nature tiene oficinas en Londres, Nueva York, ...
4814    La editorial publica también varias revistas e...
Name: Text, dtype: object

In [ ]:
df_fre = df[df['Language'] == 'French']['Text']
df_fre.head()

3250    Si vous disposez d'ouvrages ou d'articles de r...
3251                        Comment ajouter mes sources ?
3252    Cette page ou section est en train d'être trad...
3253    Vous pouvez aider au développement de Wikipédi...
3254    Le mot nature est un terme polysémique (c’est-...
Name: Text, dtype: object

In [ ]:
df_dutch = df[df['Language'] == 'Dutch']['Text']
df_dutch.head()

4264    Nature (Engels voor 'natuur') is een Brits voo...
4265                   Het staat als gerenommeerd bekend.
4266    Het verscheen voor het eerst op 4 november 186...
4267    Het groeide uit van een eenvoudige publicatie ...
4268    Een publicatie in Nature wordt door wetenschap...
Name: Text, dtype: object

In [39]:
df_danish = df[df['Language'] == 'Danish']['Text']
df_danish.head()

6686    Nature er et britisk multidisciplinært vidensk...
6687    [1] Det er rangeret som verdens mest citerede ...
6688    [2][3] Det er et af de få tilbageværende akade...
6689    [3][4] Tidsskriftets primære målgruppe er fors...
6690    I starten af hvert tidsskrift er ledere, nyhed...
Name: Text, dtype: object

In [42]:
df_it = df[df['Language'] == 'Italian']['Text']
df_it.head()

7114    Nature è una delle più antiche ed importanti r...
7115        [1] Viene pubblicata fin dal 4 novembre 1869.
7116    [2] Nonostante la maggior parte delle riviste ...
7117    Molti sono gli avanzamenti e le scoperte, prov...
7118    Il fattore di impatto (impact factor) di quest...
Name: Text, dtype: object

In [ ]:
for char in string.punctuation:
  print(char, end=" ")
translate_table = dict((ord(char), None) for char in string.punctuation)

! " # $ % & ' ( ) * + , - . / : ; < = > ? @ [ \ ] ^ _ ` { | } ~ 

In [ ]:
import re
data_eng = []
lang_eng = []
for line in df_eng:
  if len(line) !=0:
    line = line.lower()
    line = re.sub(r"\d+", "", line)
    line = line.translate(translate_table)
    data_eng.append(line)
    lang_eng.append("English")

In [ ]:
print(data_eng)
print(lang_eng)

[' nature in the broadest sense is the natural physical material world or universe', 'nature can refer to the phenomena of the physical world and also to life in general', 'the study of nature is a large if not the only part of science', 'although humans are part of nature human activity is often understood as a separate category from other natural phenomena', ' the word nature is borrowed from the old french nature and is derived from the latin word natura or essential qualities innate disposition and in ancient times literally meant birth', ' in ancient philosophy natura is mostly used as the latin translation of the greek word physis φύσις which originally related to the intrinsic characteristics that plants animals and other features of the world develop of their own accord', ' \nthe concept of nature as a whole the physical universe is one of several expansions of the original notion it began with certain core applications of the word φύσις by presocratic philosophers though this 

In [ ]:
data_ger = []
lang_ger = []
for line in df_ger:
  if len(line) !=0:
    line = line.lower()
    line = re.sub(r"\d+", "", line)
    line = line.translate(translate_table)
    data_ger.append(line)
    lang_ger.append("German")

In [ ]:
print(data_ger)
print(lang_ger)

['wir sind alle auf der suche nach schnellen wegen um fließender englisch zu sprechen', 'ich weiß ich verstehe was passiert ist dass nur ein paar worte unser gehirn umkreisen und wir diese gesamte unterhaltung mit einfach unglaublich cool oder episch führen müssen', 'wie wäre es also mit uns', 'lernen sie einige intelligente neue englische wörter die sie in ihrem täglichen leben verwenden können und erweitern sie ihren wortschatz in wenigen minuten', 'also werden wir heute  neue intelligente wörter lernen deren bedeutung wurzelwörter und beispielsätze sind', 'also lasst uns loslegen hey das ist alles und ihr schaut zu', 'und in diesem video werde ich dir  kluge worte für den täglichen gebrauch und am ende dieses videos geben', 'ich werde ihnen auch einen intelligenten tipp geben um eine wirklich fließende intelligente wortnummer zu klingen', 'man ist überflutet überflutet bedeutet ertrinken oder überfluten aber überflutet wird oft im zusammenhang mit arbeiten wie i verwendet', 'ich bin

In [ ]:
data_dutch = []
lang_dutch = []
for line in df_dutch :
  if len(line) !=0:
    line = line.lower()
    line = re.sub(r"\d+", "", line)
    line = line.translate(translate_table)
    data_dutch.append(line)
    lang_dutch.append("Dutch")

In [ ]:
print(data_dutch)
print(lang_dutch)

['nature engels voor natuur is een brits vooral natuurwetenschappelijk tijdschrift', 'het staat als gerenommeerd bekend', 'het verscheen voor het eerst op  november  en werd opgericht door de amateurastronoom norman lockyer', 'het groeide uit van een eenvoudige publicatie voor amateurwetenschappers tot een van de meest gerenommeerde wetenschappelijke tijdschriften', 'een publicatie in nature wordt door wetenschappers zeer hoog aangeslagen', 'er zijn geen tijdschriften met een hogere impactfactor behalve misschien science dat met nature om de toppositie concurreert', 'de impactfactor van nature schommelt rond de bron', 'hoewel nature een lichte nadruk op biologie legt accepteert het artikelen uit allerlei wetenschappelijke vakgebieden', 'er zijn inmiddels diverse speciale edities die zich met aparte vakgebieden bezighouden verder bestaan er nog enkele edities van nature reviews waarin hoogkwalitatieve overzichtsartikelen verschijnen', 'gemeinsame normdatei bibliotheek van het japanse pa

In [ ]:
data_spa = []
lang_spa = []
for line in df_spa :
  if len(line) !=0:
    line = line.lower()
    line = re.sub(r"\d+", "", line)
    line = line.translate(translate_table)
    data_spa.append(line)
    lang_spa.append("Spanish")

In [ ]:
print(data_spa)
print(lang_spa)

['nature es una de las más prestigiosas revistas científicas a nivel mundial\u200b que fue fundada por joseph norman lockyer', 'su primer número fue publicado el  de noviembre de ', '\u200b con una periodicidad semanal la revista es publicada en reino unido por la compañía nature publishing group subsidiaria de macmillan publishers propiedad del grupo editorial holtzbrinck dueños del semanario die zeit', 'nature tiene oficinas en londres nueva york san francisco washington d c tokio parís múnich y basingstoke y dispone de corresponsales propios en la mayoría de los países industrializados', 'la editorial publica también varias revistas especializadas bajo el nombre de nature como nature neuroscience nature methods y nature structural and molecular biology entre otros títulos', 'la revista es leída por científicos e investigadores de todo el mundo siendo la mayor parte de los artículos exposiciones de trabajos de investigación muy técnicos', 'sin embargo también incluye editoriales y no

In [ ]:
data_fre = []
lang_fre = []
for line in df_fre :
  if len(line) !=0:
    line = line.lower()
    line = re.sub(r"\d+", "", line)
    line = line.translate(translate_table)
    data_fre.append(line)
    lang_fre.append("French")

In [ ]:
print(data_fre)
print(lang_fre)

['si vous disposez douvrages ou darticles de référence ou si vous connaissez des sites web de qualité traitant du thème abordé ici merci de compléter larticle en donnant les références utiles à sa vérifiabilité et en les liant à la section «\xa0notes et références\xa0» en pratique\xa0 quelles sources sont attendues\xa0', 'comment ajouter mes sources\xa0', 'cette page ou section est en train dêtre traduite en français à partir de larticle wikipédia nature rédigé en anglais raison pour laquelle il peut y avoir des lacunes dans le contenu des erreurs syntaxiques voire du texte non traduit', 'vous pouvez aider au développement de wikipédia en continuant la traduction à partir de larticle original', 'le mot nature est un terme polysémique c’estàdire quil a plusieurs sens\xa0 il peut signifier la composition et la matière dune chose ce quelle est son essence lorigine et le devenir dune chose lensemble du réel indépendant de la culture humaine ou lensemble des systèmes et des phénomènes natur

In [40]:
data_danish = []
lang_danish = []
for line in df_danish :
  if len(line) !=0:
    line = line.lower()
    line = re.sub(r"\d+", "", line)
    line = line.translate(translate_table)
    data_danish.append(line)
    lang_danish.append("Danish")

In [41]:
print(data_danish)
print(lang_danish)

['nature er et britisk multidisciplinært videnskabeligt tidsskrift der blev udgivet første gang den  november ', ' det er rangeret som verdens mest citerede videnskabelige tidsskrift af science edition i udgaven journal citation reports og har en ifaktor på  hvilket gør det til verdens mest citerede akademiske magasin', ' det er et af de få tilbageværende akademiske tidsskrifter der udgiver original forskning spredt over en bred række videnskabelige emner', ' tidsskriftets primære målgruppe er forskere men resuméer og medfølgende artikler fremstilles for at gøre de fleste af de vigtigste artikler forståelige for videnskabsfolk inden for andre felter og den uddannede offentlighed', 'i starten af hvert tidsskrift er ledere nyheder og featureartikler som har generel interesse for videnskabsfolk inklusive nye opdagelser videnskabsetik og videnskabelige gennembrud', 'der er også sektioner med bøger og kunst', 'resten af tidsskriftet består primært af videnskabelige artikler der ofte er tæts

In [43]:
data_it = []
lang_it = []
for line in df_it :
  if len(line) !=0:
    line = line.lower()
    line = re.sub(r"\d+", "", line)
    line = line.translate(translate_table)
    data_it.append(line)
    lang_it.append("Italian")

In [44]:
print(data_it)
print(lang_it)

['nature è una delle più antiche ed importanti riviste scientifiche esistenti forse in assoluto quella considerata di maggior prestigio nellambito della comunità scientifica internazionale insieme a science', ' viene pubblicata fin dal  novembre ', ' nonostante la maggior parte delle riviste del campo siano oggi altamente specializzate nature è uno dei pochi giornali insieme ad altri mensili quali science e proceedings of the national academy of sciences che pubblica ancora articoli originali su svariati campi scientifici', 'molti sono gli avanzamenti e le scoperte provenienti da molti campi della ricerca scientifica che sono stati pubblicati su nature come articoli o lettere ad esempio la scoperta dei raggi x la natura ondulatoria delle particelle la scoperta dei neutroni le scoperte sulla fissione nucleare la struttura a doppia elica del dna la prima struttura molecolare di una proteina la mioglobina la tettonica a zolle il buco dellozono la prima clonazione di un mammifero la pecora

In [45]:
final_data = pd.DataFrame({"Text":data_eng+data_ger+data_fre+data_spa+data_dutch+data_danish+data_it, "Language":lang_eng+lang_ger+lang_fre+lang_spa+lang_dutch+lang_danish+lang_it})

In [46]:
print(final_data.shape)

(5360, 2)


In [47]:
final_data.head()

Text Language
0   nature in the broadest sense is the natural p...  English
1  nature can refer to the phenomena of the physi...  English
2  the study of nature is a large if not the only...  English
3  although humans are part of nature human activ...  English
4   the word nature is borrowed from the old fren...  English

In [48]:
x ,y = final_data.iloc[:,0],final_data.iloc[:,1]
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2,random_state=0)

In [49]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(4288,)
(1072,)
(4288,)
(1072,)


In [50]:
vectorizer = feature_extraction.text.TfidfVectorizer(ngram_range=(1,3),analyzer='char')

pipe_lr_r13 = pipeline.Pipeline([
                                 ('vectorizer', vectorizer),
                                 ('clf', linear_model.LogisticRegression())
])

pipe_lr_r13.fit(X_train,y_train)

Pipeline(memory=None,
         steps=[('vectorizer',
                 TfidfVectorizer(analyzer='char', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 3), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, use_idf=True,
                                 vocabulary=None)),
                ('clf',
                 LogisticRegression(C=1.0, class_weight=None, dual=False,
                                    fit_intercept=True, intercept_sc

In [51]:
y_predicted = pipe_lr_r13.predict(X_test)

acc = (metrics.accuracy_score(y_test, y_predicted))*100
print(acc,'%')

98.41417910447761 %


In [52]:
matrix = metrics.confusion_matrix(y_test, y_predicted)
print('Confusion matrix: \n', matrix)

Confusion matrix: 
 [[ 85   0   1   0   0   0   0]
 [  0 104   1   0   0   0   0]
 [  0   1 275   1   0   2   0]
 [  0   1   1 187   0   2   0]
 [  1   0   0   0  91   0   0]
 [  0   0   0   1   0 150   2]
 [  0   0   1   1   0   1 163]]


In [64]:
import pickle
lrFile = open('drive/MyDrive/Language Detection Model/LRModel.pckl','wb')
pickle.dump(pipe_lr_r13, lrFile)
lrFile.close()

In [54]:
def lang_detect(text):
  import numpy as np
  import string
  import re
  import pickle
  translate_table = dict((ord(char), None) for char in string.punctuation)

  global lrLangDetectionModel
  lrLangDetectionFile = open('LRModel.pckl', 'rb')
  lrLangDetectionModel= pickle.load(lrLangDetectionFile)
  lrLangDetectionFile.close()

  text = " ".join(text.split())
  text = text.lower()
  text = re.sub(r"\d+", "", text)
  text = text.translate(translate_table)
  pred = lrLangDetectionModel.predict([text])
  prob = lrLangDetectionModel.predict_proba([text])
  return pred[0]


In [55]:
lang_detect("Wir haben die Keks gebracht.")

'German'

In [56]:
lang_detect("Quiero aprender español")

'Spanish'

In [57]:
lang_detect("Questo premio fu accompagnato da un finanziamento di 10.000 euro e da un invito a presenziare al PAE Cyberarts Festival di quell'anno.")

'Italian'

In [58]:
lang_detect("Hello how are you?")

'English'

In [59]:
lang_detect("Hej! Jeg hedder Morten. Hvad hedder du?")

'Danish'

In [60]:
lang_detect("Apprendre à lire")

'French'

In [61]:
lang_detect("Waar komt u vandaan?")

'Dutch'